#------------------------------------------------------
#Repository - place-management - Service: NodePort
#------------------------------------------------------
apiVersion: v1
kind: Service     # Type/Kind of Work/Function which cluster will interpret to do
metadata:
  name: place

spec:             #This defines which pods are going to be represented by this Service
  selector:       #The service becomes a network endpoint for other services or maybe external uses to connect to (ex: browser)
    app: place

  ports:
    - name: http
      port: 8084        #this is Service port
      nodePort: 30084  #this is Node port
  type: NodePort

---

#---------------------------------------------------
#Database - mysql-place - Service: Cluster
#---------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql-place   #network name

spec:
  selector:
    app: mysql-place  #pod identification

  ports:
    - name: mysql-place-endpoint
      port: 3306
  type: ClusterIP

---
