version: '3'

# ------------------------------
# authorization-server instances
# ------------------------------

services:
  mysql-authorization-server:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - /var/takeyourseatapi_dev/mysql-authorization-server:/var/takeyourseatapi_dev/mysql-authorization-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  authorization-server:
#    image: capostol93/authorization-server
    build: ./authorization-server
    ports:
      - '8086:8086'
    volumes:
      - /var/takeyourseatapi_dev/authorization-server:/var/takeyourseatapi_dev/authorization-server
    restart: always
    depends_on:
      -  mysql-authorization-server
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-authorization-server:3306/test'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.106/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

# ------------------------------
# oauth-server instances
# ------------------------------

  mysql-oauth-server:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - /var/takeyourseatapi_dev/mysql-oauth-server:/var/takeyourseatapi_dev/mysql-oauth-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  oauth-server:
#    image: capostol93/oauth-server
    build: ./oauth-server
    ports:
      - '8083:8083'
    volumes:
      - /var/takeyourseatapi_dev/oauth-server:/var/takeyourseatapi_dev/oauth-server
    restart: always
    depends_on:
      -  mysql-oauth-server
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-oauth-server:3306/test'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.112/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

# ------------------------------
# place-management instances
# ------------------------------

  mysql-place-management:
    image: mysql
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - /var/takeyourseatapi_dev/mysql-place-management:/var/takeyourseatapi_dev/mysql-place-management
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  place-management:
#    image: capostol93/place-management
    build: ./place-management
    ports:
      - '8084:8084'
    volumes:
      - /var/takeyourseatapi_dev/place-management:/var/takeyourseatapi_dev/place-management
    restart: always
    depends_on:
      -  mysql-place-management
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-place-management:3306/test'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.112/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

# ------------------------------
# user-management instances
# ------------------------------

  mysql-user-management:
    image: mysql
    restart: always
    ports:
      - '3309:3306'
    volumes:
      - /var/takeyourseatapi_dev/mysql-user-management:/var/takeyourseatapi_dev/mysql-user-management
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  user-management:
#    image: capostol93/user-management
    build: ./user-management
    ports:
      - '8085:8085'
    volumes:
      - /var/takeyourseatapi_dev/user-management:/var/takeyourseatapi_dev/user-management
    restart: always
    depends_on:
      - mysql-user-management
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-user-management:3306/test'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.112/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3