version: '3'

services:
  mysql-authorization-server:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  authorization-server:
#    image: authorization-server:3
    build: ./authorization-server
    ports:
      - '8086:8086'
    restart: always
    depends_on:
      -  mysql-authorization-server
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-authorization-server:3306/test'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.106/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

