version: '3'

services:
  mysql-oauth-server:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    networks:
      - host
    volumes:
      - /var/takeyourseatapi_dev/mysql-oauth-server:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password


  oauth-server:
    #    image: capostol93/oauth-server
    build: ./oauth-server
    ports:
      - '8083:8083'
    restart: always
    depends_on:
      - mysql-oauth-server
    networks:
      - host
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-oauth-server:3306/test'
      SPRING_PROFILES_ACTIVE: 'dockercompose'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.112/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mysql-place-management:
    image: mysql
    restart: always
    ports:
      - '3308:3306'
    networks:
      - host
    volumes:
      - /var/takeyourseatapi_dev/mysql-place-management:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  place-management:
    #    image: capostol93/place-management
    build: ./place-management
    ports:
      - '8084:8084'
    restart: always
    depends_on:
      -  mysql-place-management
    networks:
      - host
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-place-management:3306/test'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.112/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  host:
