#------------------------------------------------------
#Repository - user-management - Service: NodePort
#------------------------------------------------------
apiVersion: v1
kind: Service     # Type/Kind of Work/Function which cluster will interpret to do
metadata:
  name: user

spec:             #This defines which pods are going to be represented by this Service
  selector:       #The service becomes a network endpoint for other services or maybe external uses to connect to (ex: browser)
    app: user

  ports:
    - name: http
      port: 8085        #this is Service port
      nodePort: 30085  #this is Node port
  type: NodePort

---

#---------------------------------------------------
#Database - mysql-user - Service: Cluster
#---------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql-user   #network name

spec:
  selector:
    app: mysql-user  #pod identification

  ports:
    - name: mysql-user-endpoint
      port: 3306
  type: ClusterIP

---
