apiVersion: v1

# kind of function which we will provoide to kubernetes cluster
kind: Pod

#data related to the object inside the "Pod"
metadata:
  name: authorization-server #pod name
  labels:
    app: authorization-server #app name
    type: back-end

#Here we will provide aditional information for kubernates
spec:
  containers:
    - name:  authorization-server-container #name of the docker file
      image: capostol93/authorization-server  #name of the docker file to download