apiVersion: v1

# kind of function which we will provoide to kubernetes cluster
kind: Pod

#data related to the object inside the "Pod"
metadata:
  name: oauth-server-pod #pod name
  labels:
    name: oauth-server-pod
    app: takeyourseat #app name
    type: back-end


#Here we will provide aditional information for kubernates
spec:
  containers:
    - name:  oauth-server #name of the docker file
      image: capostol93/oauth-server  #name of the docker file to download
      ports:
       - containerPort: 8083