apiVersion: apps/v1
kind: Deployment

metadata:
  name: webapp

spec:
#  minReadySecond: 30
  selector: #manage any pod where label is equal to what we ad
    matchLabels:
      app: front-end

  replicas: 1

  template: # template for the pods
    metadata:
      labels:
        name: webapp
        app: front-end
    spec:
      containers:
        - name: portal-app
          image: capostol93/portal-app
          ports:
            - containerPort: 80

---

#-------------------------------
#BackEnd - user - Pod
#-------------------------------
apiVersion: apps/v1
kind: Deployment

metadata:
  name: backapp

spec:
  selector:
    matchLabels:
      app: backapp

  replicas: 1

  template:
    metadata:
      labels:
        app: backapp
    spec:
      containers:
      - name: user-app
        image: capostol93/user-app
        ports:
          - containerPort: 8083
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes

---

#-------------------------------------
#Repository - mysql - Pod
#-------------------------------------
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql

spec:
  selector:
    matchLabels:
      app: mysql

  replicas: 1

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "testdb"
            - name: MYSQL_USER
              value: "sa"
            - name: MYSQL_PASSWORD
              value: "password"
---
