version: '3'

services:
  place-notification-builder:
#    image: place-notification-builder
    build: .
    ports:
      - '8088:8088'
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://167.71.46.25/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
