#-------------------------------
#FrontEnd - portal-app - Pod
#-------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    name: webapp
    app: front-end
spec:
  containers:
    - name: portal-app
      image: capostol93/portal-app
      ports:
      - containerPort: 80

---

#-------------------------------
#BackEnd - user-portal - Pod
#-------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: backapp
  labels:
    name: backapp
    app: back-end
spec:
  containers:
    - name: user-app
      image: capostol93/user-app
      ports:
        - containerPort: 8083

---

#-------------------------------------
#Repository - mysql-standalone - Pod
#-------------------------------------
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    app: db
spec:
  containers:
    - name: mysql-standalone
      image: mysql
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "password"
      - name: MYSQL_DATABASE
        value: "testdb"
      - name: MYSQL_USER
        value: "sa"
      - name: MYSQL_PASSWORD
        value: "password"
---
