server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/takeyourseat_oauth_dev?createDatabaseIfNotExist=true
    username: admin
    password: toor
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: debug