version: '3'

services:
  mysql-place-management:
    image: mysql
    restart: always
    ports:
      - '3310:3306'
    volumes:
      - /var/takeyourseat/docker-volumes/mysql-place-management:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  place-management:
#    image: capostol93/place-management
    build: .
    ports:
      - '8084:8084'
    restart: always
    depends_on:
      -  mysql-place-management
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-place-management:3306/test'
      SPRING_PROFILES_ACTIVE: 'dockercompose'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://167.71.46.25/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
