version: '3'

services:
  mysql-authorization-server:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - /var/takeyourseat/docker-volumes/mysql-authorization-server:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  authorization-server:
#    image: authorization-server
    build: .
    ports:
      - '8086:8086'
    restart: always
    depends_on:
      -  mysql-authorization-server
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-authorization-server:3306/test'
      SPRING_PROFILES_ACTIVE: 'dockercompose'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://167.71.46.25/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

